{
 "title": "Openwrt Collectd Graph Panel (Flux)",
 "description": "Inspired by the Openwrt dashboard and original Collectd Graph Panel (PHP frontend), but then as a Dashboard in Grafana with InfluxDB as a data source. Similar colors and styling. Currently supported graphs: - Load - CPU - Memory - Interface Traffic (Original: https://collectd.org/wiki/index.php/Collectd_Graph_Panel)",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "import \"influxdata/influxdb/schema\"\n \nschema.tagValues(\n  bucket: \"${dynamicbucket}\",\n  tag: \"host\",\n  predicate: (r) => r[\"_field\"] == \"value\",\n  start: v.timeRangeStart, \n  stop: v.timeRangeStop\n)"
   },
   {
    "name": "client",
    "label": "Client",
    "query": "import \"influxdata/influxdb/schema\"\r\n \r\nschema.tagValues(\r\n  bucket: \"${dynamicbucket}\",\r\n  tag: \"type_instance\",\r\n  predicate: (r) => r[\"_measurement\"] == \"iptables_value\",\r\n  start: v.timeRangeStart, \r\n  stop: v.timeRangeStop\r\n)"
   },
   {
    "name": "interface",
    "label": "Interface",
    "query": "import \"influxdata/influxdb/schema\"\r\n \r\nschema.tagValues(\r\n  bucket: \"${dynamicbucket}\",\r\n  tag: \"instance\",\r\n  predicate: (r) => r[\"_measurement\"] == \"interface_rx\" and r[\"host\"] =~ /^$hostname$/ and r[\"aggregate\"] == \"${agg}\",\r\n  start: v.timeRangeStart, \r\n  stop: v.timeRangeStop\r\n)"
   },
   {
    "name": "wifi_if",
    "label": "Wi-Fi Interface",
    "query": "import \"influxdata/influxdb/schema\"\r\n \r\nschema.tagValues(\r\n  bucket: \"${dynamicbucket}\",\r\n  tag: \"instance\",\r\n  predicate: (r) => r[\"_measurement\"] == \"iwinfo_value\" and r[\"host\"] =~ /^$hostname$/ and r[\"aggregate\"] == \"${agg}\",\r\n  start: v.timeRangeStart, \r\n  stop: v.timeRangeStop\r\n)"
   },
   { "name": "agg", "label": "Aggregation Type", "query": "max, mean, min" },
   {
    "name": "cpuid",
    "query": "import \"influxdata/influxdb/schema\"\r\n \r\nschema.tagValues(\r\n  bucket: \"${dynamicbucket}\",\r\n  tag: \"instance\",\r\n  predicate: (r) => r[\"_measurement\"] == \"cpu_value\" and r[\"host\"] =~ /^$hostname$/ and r[\"aggregate\"] == \"${agg}\",\r\n  start: v.timeRangeStart, \r\n  stop: v.timeRangeStop\r\n)"
   },
   {
    "name": "dynamicbucket",
    "label": "Retention Policy",
    "query": "//Bucketfilter to filter only buckets beginning with name telegraf..\r\nbucketfilter = /collectd\\/[^af].*/\r\n\r\nbuckets()\r\n  |> filter(fn: (r) => r.name =~ bucketfilter)\r\n  //convert retentionperiod from nanosecond to days\r\n  |> map(fn: (r) => ({r with \r\n    retentionPeriodinDays: r.retentionPeriod / 86400000000000}) \r\n  )\r\n  //replace retentionpolicy infinity with a high number in NS\r\n  |> map(fn: (r) => ({r with\r\n    retentionPeriod: if r.retentionPeriod == 0 then 999999999999999999\r\n    else r.retentionPeriod})\r\n  )\r\n  //calculate the duration from \"to\" and \"from\" timespan and convert it to nanosecond\r\n  |> map(fn: (r) => ({r with \r\n    DashboardDurationinNS: (${__to} - ${__from}) * 1000000})\r\n  )\r\n  |> filter(fn: (r) => \r\n    r.DashboardDurationinNS <= r.retentionPeriod and\r\n    r.retentionPeriod >= uint(v: now()) - uint(v: ${__from} * 1000000)\r\n  )\r\n  |> sort(columns: [\"retentionPeriod\"], desc: false)\r\n  |> limit(n: 1)\r\n  |> keep(columns: [\"name\"]) //remove all fields except for \"name\""
   },
   {
    "name": "cNVThreshold",
    "label": "connectNullValuesThreshold",
    "query": "//Bucketfilter to filter only buckets beginning with name telegraf..\r\nbucketfilter = /collectd\\/[^af].*/\r\n\r\nbuckets()\r\n  |> filter(fn: (r) => r.name == \"${dynamicbucket}\")\r\n  //convert retentionperiod from nanosecond to days\r\n  |> map(fn: (r) => ({r with \r\n    retentionPeriodinSeconds: r.retentionPeriod /1000 }) \r\n  )\r\n    |> map(fn: (r) => ({r with \r\n    retentionPeriodString: string(v: duration(v: uint(v: r.retentionPeriodinSeconds)))})\r\n  )\r\n    |> keep(columns: [\"retentionPeriodString\"]) //remove all fields except for \"name\""
   }
  ]
 },
 "panels": [
  {
   "title": "System Load on $hostname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "query": "from(bucket: \"${dynamicbucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"load_longterm\")\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"aggregate\"] == \"${agg}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: ${agg}, createEmpty: true)\n  |> yield(name: \"longterm\")\n\nfrom(bucket: \"${dynamicbucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"load_midterm\")\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"aggregate\"] == \"${agg}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"midterm\")\n\nfrom(bucket: \"${dynamicbucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"load_shortterm\")\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"aggregate\"] == \"${agg}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"shortterm\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "used" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage on $hostname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "query": "from(bucket: \"${dynamicbucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"memory_value\")\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"aggregate\"] == \"${agg}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: ${agg}, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "used" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage on $hostname on CPU ${cpuid}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "repeat": "cpuid",
   "targets": [
    {
     "query": "from(bucket: \"${dynamicbucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_value\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"aggregate\"] == \"${agg}\")\r\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\r\n  |> filter(fn: (r) => r[\"instance\"] =~ /^${cpuid}$/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: ${agg}, createEmpty: true)"
    }
   ]
  },
  {
   "title": "Interface Traffic ($interface) on $hostname",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 17 },
   "repeat": "interface",
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "Receive",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "interface_rx",
     "query": "from(bucket: \"${dynamicbucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"type\"] == \"if_octets\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"instance\"] =~ /^${interface}$/)\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface_tx\")\r\n  |> filter(fn: (r) => r[\"aggregate\"] == \"${agg}_rate\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: ${agg}, createEmpty: true)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_octets" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$interface$/" }
     ]
    },
    {
     "alias": "Transmit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "interface_tx",
     "query": "from(bucket: \"${dynamicbucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"type\"] == \"if_octets\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface_rx\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\r\n  |> filter(fn: (r) => r[\"instance\"] =~ /^${interface}$/)\r\n  |> filter(fn: (r) => r[\"aggregate\"] == \"${agg}_rate\")\r\n  //|> set(key: \"_field\", value: \"Receive\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_octets" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$interface$/" }
     ]
    }
   ]
  },
  {
   "title": "TX Total on $hostname",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${dynamicbucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface_tx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\n  |> filter(fn: (r) => r[\"instance\"] =~ /^${interface:regex}$/)\n  |> filter(fn: (r) => r[\"aggregate\"] == \"increase\")\n  |> filter(fn: (r) => r[\"type\"] == \"if_octets\")\n  |> sum()\n  |> keep(columns: [\"instance\", \"_value\"])\n  |> group()\n  \n  |> yield(name: \"sum\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RX Total on $hostname",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${dynamicbucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface_rx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\n  |> filter(fn: (r) => r[\"instance\"] =~ /^${interface:regex}$/)\n  |> filter(fn: (r) => r[\"type\"] == \"if_octets\")\n  |> filter(fn: (r) => r[\"aggregate\"] == \"increase\")\n  |> sum()\n  |> keep(columns: [\"instance\", \"_value\"])\n  |> group()\n  |> yield(name: \"sum\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TX client Traffic on $hostname",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 17, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "Receive",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "interface_rx",
     "query": "from(bucket: \"${dynamicbucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iptables_value\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"aggregate\"] == \"${agg}_rate\")\r\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\r\n  |> filter(fn: (r) => r[\"instance\"] == \"mangle-iptmon_tx\")\r\n  |> filter(fn: (r) => r[\"type_instance\"] =~ /^tx_${client:regex}$/)\r\n  |> filter(fn: (r) => r[\"type\"] == \"ipt_bytes\")\r\n  //|> fill(value: 0.0)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: ${agg}, createEmpty: true)\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_octets" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$interface$/" }
     ]
    }
   ]
  },
  {
   "title": "TX Total on $hostname",
   "type": "table",
   "gridPos": { "h": 12, "w": 5, "x": 17, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${dynamicbucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iptables_value\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"aggregate\"] == \"increase\")\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\n  |> filter(fn: (r) => r[\"instance\"] == \"mangle-iptmon_tx\")\n  |> filter(fn: (r) => r[\"type_instance\"] =~ /^tx_${client:regex}$/)\n  |> filter(fn: (r) => r[\"type\"] == \"ipt_bytes\")\n  |> sum()\n  |> keep(columns: [\"type_instance\",\"_value\"])  \n  |> group()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RX client Traffic on $hostname",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 17, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "Transmit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "interface_tx",
     "query": "from(bucket: \"${dynamicbucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iptables_value\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"aggregate\"] == \"${agg}_rate\")\r\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\r\n  |> filter(fn: (r) => r[\"instance\"] == \"mangle-iptmon_rx\")\r\n  |> filter(fn: (r) => r[\"type_instance\"] =~ /^rx_${client:regex}$/)\r\n  |> filter(fn: (r) => r[\"type\"] == \"ipt_bytes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: ${agg}, createEmpty: true)\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_octets" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$interface$/" }
     ]
    }
   ]
  },
  {
   "title": "RX Total on $hostname",
   "type": "table",
   "gridPos": { "h": 12, "w": 5, "x": 17, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${dynamicbucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iptables_value\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"aggregate\"] == \"increase\")\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\n  |> filter(fn: (r) => r[\"instance\"] == \"mangle-iptmon_rx\")\n  |> filter(fn: (r) => r[\"type_instance\"] =~ /^rx_${client:regex}$/)\n  |> filter(fn: (r) => r[\"type\"] == \"ipt_bytes\")\n  |> sum()\n  |> keep(columns: [\"type_instance\",\"_value\"])  \n  |> group()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TX client Traffic on $hostname (Nlbwmon)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 17, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "Receive",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "interface_rx",
     "query": "from(bucket: \"${dynamicbucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iptables_value\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"aggregate\"] == \"${agg}_rate\")\r\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\r\n  |> filter(fn: (r) => r[\"instance\"] == \"mangle-nlbwmon_tx\")\r\n  |> filter(fn: (r) => r[\"type_instance\"] =~ /^tx_${client:regex}$/)\r\n  |> filter(fn: (r) => r[\"type\"] == \"ipt_bytes\")\r\n  //|> fill(value: 0.0)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: ${agg}, createEmpty: true)\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_octets" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$interface$/" }
     ]
    }
   ]
  },
  {
   "title": "TX Total on $hostname (Nlbwmon)",
   "type": "table",
   "gridPos": { "h": 12, "w": 5, "x": 17, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${dynamicbucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iptables_value\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"aggregate\"] == \"increase\")\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\n  |> filter(fn: (r) => r[\"instance\"] == \"mangle-nlbwmon_tx\")\n  |> filter(fn: (r) => r[\"type_instance\"] =~ /^tx_${client:regex}$/)\n  |> filter(fn: (r) => r[\"type\"] == \"ipt_bytes\")\n  |> sum()\n  |> keep(columns: [\"type_instance\",\"_value\"])  \n  |> group()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RX client Traffic on $hostname (Nlbwmon)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 17, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "Receive",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "interface_rx",
     "query": "from(bucket: \"${dynamicbucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iptables_value\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"aggregate\"] == \"${agg}_rate\")\r\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\r\n  |> filter(fn: (r) => r[\"instance\"] == \"mangle-nlbwmon_rx\")\r\n  |> filter(fn: (r) => r[\"type_instance\"] =~ /^rx_${client:regex}$/)\r\n  |> filter(fn: (r) => r[\"type\"] == \"ipt_bytes\")\r\n  //|> fill(value: 0.0)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: ${agg}, createEmpty: true)\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_octets" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$interface$/" }
     ]
    }
   ]
  },
  {
   "title": "RX Total on $hostname (Nlbwmon)",
   "type": "table",
   "gridPos": { "h": 12, "w": 5, "x": 17, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${dynamicbucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iptables_value\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"aggregate\"] == \"increase\")\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\n  |> filter(fn: (r) => r[\"instance\"] == \"mangle-nlbwmon_rx\")\n  |> filter(fn: (r) => r[\"type_instance\"] =~ /^rx_${client:regex}$/)\n  |> filter(fn: (r) => r[\"type\"] == \"ipt_bytes\")\n  |> sum()\n  |> keep(columns: [\"type_instance\",\"_value\"])  \n  |> group()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wifi Data rate on $hostname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"${dynamicbucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iwinfo_value\")\r\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"aggregate\"] == \"${agg}\")\r\n  |> filter(fn: (r) => r[\"instance\"] =~ /^${wifi_if:regex}$/) \r\n  |> filter(fn: (r) => r[\"type\"] == \"bitrate\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: ${agg}, createEmpty: true)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Wifi Clients on $hostname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 101 },
   "targets": [
    {
     "query": "from(bucket: \"${dynamicbucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iwinfo_value\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"aggregate\"] == \"${agg}\")\r\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\r\n  |> filter(fn: (r) => r[\"instance\"] =~ /^${wifi_if:regex}$/) \r\n  |> filter(fn: (r) => r[\"type\"] == \"stations\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: ${agg}, createEmpty: true)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Connections on $hostname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 109 },
   "targets": [
    {
     "query": "from(bucket: \"${dynamicbucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"conntrack_value\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\r\n  |> filter(fn: (r) => r[\"type\"] == \"conntrack\")\r\n  |> filter(fn: (r) => r[\"type_instance\"] != \"max\")\r\n  |> filter(fn: (r) => r[\"aggregate\"] == \"${agg}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: ${agg}, createEmpty: true)"
    }
   ]
  },
  {
   "title": "DNS requests/sec on $hostname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 109 },
   "targets": [
    {
     "query": "from(bucket: \"${dynamicbucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dns_value\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"aggregate\"] == \"${agg}_rate\")\r\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: ${agg}, createEmpty: true)\r\n"
    }
   ]
  },
  {
   "title": "DHCP leases on $hostname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 109 },
   "targets": [
    {
     "query": "from(bucket: \"${dynamicbucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dhcpleases_value\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"aggregate\"] == \"${agg}\")\r\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: ${agg}, createEmpty: true)\r\n"
    }
   ]
  }
 ]
}