{
 "title": "Collectd Graph Panel Flux",
 "description": "Like the original Collectd Graph Panel (PHP frontend), but then as a Dashboard in Grafana with InfluxDB as a data source. Same colors and styling. Currently supported graphs: - Load - CPU - Memory - Swap - Disk Traffic - Disk Usage - Interface Traffic (Original: https://collectd.org/wiki/index.php/Collectd_Graph_Panel)",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "import \"influxdata/influxdb/schema\"\n \nschema.tagValues(\n  bucket: \"collectd/${rp}\",\n  tag: \"host\",\n  predicate: (r) => r[\"_field\"] == \"value\",\n  start: v.timeRangeStart, \n  stop: v.timeRangeStop\n)"
   },
   {
    "name": "client",
    "label": "Client",
    "query": "import \"influxdata/influxdb/schema\"\r\n \r\nschema.tagValues(\r\n  bucket: \"collectd/${rp}\",\r\n  tag: \"type_instance\",\r\n  predicate: (r) => r[\"_measurement\"] == \"iptables_value\",\r\n  start: v.timeRangeStart, \r\n  stop: v.timeRangeStop\r\n)"
   },
   {
    "name": "interface",
    "label": "Interface",
    "query": "import \"influxdata/influxdb/schema\"\r\n \r\nschema.tagValues(\r\n  bucket: \"collectd/${rp}\",\r\n  tag: \"instance\",\r\n  predicate: (r) => r[\"_measurement\"] == \"interface_rx\" and r[\"host\"] =~ /^$hostname$/,\r\n  start: v.timeRangeStart, \r\n  stop: v.timeRangeStop\r\n)"
   },
   {
    "name": "rp",
    "label": "Retention Policy",
    "query": "select rp from forever.rp_config where $__to-$__from > \"start\" and $__to - $__from <= \"end\""
   },
   { "name": "agg", "label": "Aggregation Type", "query": "max, mean, min" }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage on $hostname",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "used" }
     ]
    },
    {
     "alias": "Slab Unrecl.",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "slab_unrecl" }
     ]
    },
    {
     "alias": "Slab Recl.",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "slab_recl" }
     ]
    },
    {
     "alias": "Buffered",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "buffered" }
     ]
    },
    {
     "alias": "Cached",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "cached" }
     ]
    },
    {
     "alias": "Free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "free" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage on $hostname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "query": "from(bucket: \"collectd/day\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"memory_value\")\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"aggregate\"] == \"${agg}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "used" }
     ]
    }
   ]
  },
  {
   "title": "CPU usage on $hostname",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent", "label": "Jiffies" }
   ],
   "targets": [
    {
     "alias": "Steal",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "steal" }
     ]
    },
    {
     "alias": "IRQ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "interrupt" }
     ]
    },
    {
     "alias": "SoftIRQ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "softirq" }
     ]
    },
    {
     "alias": "System",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "system" }
     ]
    },
    {
     "alias": "Wait-IO",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "wait" }
     ]
    },
    {
     "alias": "User",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "user" }
     ]
    },
    {
     "alias": "Nice",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "nice" }
     ]
    },
    {
     "alias": "Idle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "idle" }
     ]
    }
   ]
  },
  {
   "title": "TX Total ($hostname)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"collectd/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface_tx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\n  |> filter(fn: (r) => r[\"type\"] == \"if_octets\")\n  |> difference(nonNegative: true, columns: [\"_value\"])\n  |> sum()\n  |> keep(columns: [\"instance\", \"_value\"])\n  |> group()\n  |> yield(name: \"sum\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RX Total ($hostname)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"collectd/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface_rx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\n  |> filter(fn: (r) => r[\"type\"] == \"if_octets\")\n  |> difference(nonNegative: true, columns: [\"_value\"])\n  |> sum()\n  |> keep(columns: [\"instance\", \"_value\"])\n  |> group()\n  |> yield(name: \"sum\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "System Load on $hostname",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "1 min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "load_shortterm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "load" }
     ]
    },
    {
     "alias": "5 min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "load_midterm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "load" }
     ]
    },
    {
     "alias": "15 min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "load_longterm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "load" }
     ]
    }
   ]
  },
  {
   "title": "Swap Usage on $hostname",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "used" }
     ]
    },
    {
     "alias": "Cached",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "cached" }
     ]
    },
    {
     "alias": "Free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "free" }
     ]
    }
   ]
  },
  {
   "title": "RX traffic ${interface} (${hostname})",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "repeat": "interface",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "//import \"date\"\n//laterTimeStart = date.add(d: 1m, to: v.timeRangeStart)\n//earlierTimeStop = date.sub(d: 1m, from: v.timeRangeStop)\n\nfrom(bucket: \"collectd/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface_rx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\n  |> filter(fn: (r) => r[\"instance\"] =~ /^${interface}$/)\n  |> filter(fn: (r) => r[\"type\"] == \"if_octets\")\n  |> difference(nonNegative: true, columns: [\"_value\"])\n  |> sum()\n\n  |> yield(name: \"sum0\")\n\n\nfrom(bucket: \"collectd/day\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface_rx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\n  |> filter(fn: (r) => r[\"instance\"] =~ /^${interface}$/)\n  |> filter(fn: (r) => r[\"type\"] == \"if_octets\")\n  |> filter(fn: (r) => r[\"aggregate\"] == \"increase\")\n//  |> difference(nonNegative: true, columns: [\"_value\"])\n  |> sum()\n  //|> keep(columns: [\"instance\", \"_value\"])\n  |> yield(name: \"sum1\")\n\n\nfrom(bucket: \"collectd/week\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface_rx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\n  |> filter(fn: (r) => r[\"instance\"] =~ /^${interface}$/)\n  |> filter(fn: (r) => r[\"type\"] == \"if_octets\")\n  |> filter(fn: (r) => r[\"aggregate\"] == \"increase\")\n// |> difference(nonNegative: true, columns: [\"_value\"])\n  |> sum()\n // |> keep(columns: [\"instance\", \"_value\"])\n  |> yield(name: \"sum2\")\n\n\n\nfrom(bucket: \"collectd/month\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface_rx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\n  |> filter(fn: (r) => r[\"instance\"] =~ /^${interface}$/)\n  |> filter(fn: (r) => r[\"type\"] == \"if_octets\")\n  |> filter(fn: (r) => r[\"aggregate\"] == \"increase\")\n  //|> difference(nonNegative: true, columns: [\"_value\"])  \n  //|> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |>sum()\n  |> yield(name: \"sum3\")\n\nfrom(bucket: \"collectd/year\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface_rx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\n  |> filter(fn: (r) => r[\"instance\"] =~ /^${interface}$/)\n  |> filter(fn: (r) => r[\"type\"] == \"if_octets\")\n  |> filter(fn: (r) => r[\"aggregate\"] == \"increase\")\n  //|> difference(nonNegative: true, columns: [\"_value\"])  \n  //|> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |>sum()\n  |> yield(name: \"sum4\")\n\nfrom(bucket: \"collectd/tenyear\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface_rx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\n  |> filter(fn: (r) => r[\"instance\"] =~ /^${interface}$/)\n  |> filter(fn: (r) => r[\"type\"] == \"if_octets\")\n  |> filter(fn: (r) => r[\"aggregate\"] == \"increase\")\n  //|> difference(nonNegative: true, columns: [\"_value\"])  \n  //|> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |>sum()\n  |> yield(name: \"sum5\")\n\n\nfrom(bucket: \"collectd/hundyear\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface_rx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\n  |> filter(fn: (r) => r[\"instance\"] =~ /^${interface}$/)\n  |> filter(fn: (r) => r[\"type\"] == \"if_octets\")\n  |> filter(fn: (r) => r[\"aggregate\"] == \"increase\")\n  //|> difference(nonNegative: true, columns: [\"_value\"])  \n  //|> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |>sum()\n  |> yield(name: \"sum6\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TX traffic ${interface} (${hostname})",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
   "repeat": "interface",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "//import \"date\"\n//laterTimeStart = date.add(d: 1m, to: v.timeRangeStart)\n//earlierTimeStop = date.sub(d: 1m, from: v.timeRangeStop)\n\nfrom(bucket: \"collectd/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface_tx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\n  |> filter(fn: (r) => r[\"instance\"] =~ /^${interface}$/)\n  |> filter(fn: (r) => r[\"type\"] == \"if_octets\")\n  |> difference(nonNegative: true, columns: [\"_value\"])\n  |> sum()\n\n  |> yield(name: \"sum0\")\n\n\nfrom(bucket: \"collectd/day\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface_tx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\n  |> filter(fn: (r) => r[\"instance\"] =~ /^${interface}$/)\n  |> filter(fn: (r) => r[\"type\"] == \"if_octets\")\n  |> filter(fn: (r) => r[\"aggregate\"] == \"increase\")\n//  |> difference(nonNegative: true, columns: [\"_value\"])\n  |> sum()\n  //|> keep(columns: [\"instance\", \"_value\"])\n  |> yield(name: \"sum1\")\n\n\nfrom(bucket: \"collectd/week\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface_tx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\n  |> filter(fn: (r) => r[\"instance\"] =~ /^${interface}$/)\n  |> filter(fn: (r) => r[\"type\"] == \"if_octets\")\n  |> filter(fn: (r) => r[\"aggregate\"] == \"increase\")\n// |> difference(nonNegative: true, columns: [\"_value\"])\n  |> sum()\n // |> keep(columns: [\"instance\", \"_value\"])\n  |> yield(name: \"sum2\")\n\n\n\nfrom(bucket: \"collectd/month\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface_tx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\n  |> filter(fn: (r) => r[\"instance\"] =~ /^${interface}$/)\n  |> filter(fn: (r) => r[\"type\"] == \"if_octets\")\n  |> filter(fn: (r) => r[\"aggregate\"] == \"increase\")\n  //|> difference(nonNegative: true, columns: [\"_value\"])  \n  //|> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |>sum()\n  |> yield(name: \"sum3\")\n\nfrom(bucket: \"collectd/year\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface_tx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\n  |> filter(fn: (r) => r[\"instance\"] =~ /^${interface}$/)\n  |> filter(fn: (r) => r[\"type\"] == \"if_octets\")\n  |> filter(fn: (r) => r[\"aggregate\"] == \"increase\")\n  //|> difference(nonNegative: true, columns: [\"_value\"])  \n  //|> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |>sum()\n  |> yield(name: \"sum4\")\n\nfrom(bucket: \"collectd/tenyear\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface_tx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\n  |> filter(fn: (r) => r[\"instance\"] =~ /^${interface}$/)\n  |> filter(fn: (r) => r[\"type\"] == \"if_octets\")\n  |> filter(fn: (r) => r[\"aggregate\"] == \"increase\")\n  //|> difference(nonNegative: true, columns: [\"_value\"])  \n  //|> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |>sum()\n  |> yield(name: \"sum5\")\n\n\nfrom(bucket: \"collectd/hundyear\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface_tx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\n  |> filter(fn: (r) => r[\"instance\"] =~ /^${interface}$/)\n  |> filter(fn: (r) => r[\"type\"] == \"if_octets\")\n  |> filter(fn: (r) => r[\"aggregate\"] == \"increase\")\n  //|> difference(nonNegative: true, columns: [\"_value\"])  \n  //|> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |>sum()\n  |> yield(name: \"sum6\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Interface Traffic ($interface) on $hostname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 33 },
   "repeat": "interface",
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "Receive",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "interface_rx",
     "query": "from(bucket: \"collectd/${rp}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"type\"] == \"if_octets\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"instance\"] =~ /^${interface}$/)\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface_tx\")\r\n  |> filter(fn: (r) => r[\"aggregate\"] == \"${agg}_rate\")\r\n  //|> set(key: \"_field\", value: \"Transmit\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_octets" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$interface$/" }
     ]
    },
    {
     "alias": "Transmit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "interface_tx",
     "query": "from(bucket: \"collectd/${rp}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"type\"] == \"if_octets\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface_rx\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\r\n  |> filter(fn: (r) => r[\"instance\"] =~ /^${interface}$/)\r\n  |> filter(fn: (r) => r[\"aggregate\"] == \"${agg}_rate\")\r\n  //|> set(key: \"_field\", value: \"Receive\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_octets" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$interface$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface Traffic ($interface) on $hostname",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "repeat": "interface",
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Receive",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "interface_rx",
     "query": "SELECT 8*non_negative_derivative(mean(\"value\"), 1s) FROM \"autogen\".\"interface_rx\" WHERE (\"host\" =~ /^$hostname$/ AND \"type\" = 'if_octets' AND \"instance\" =~ /^$interface$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_octets" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$interface$/" }
     ]
    },
    {
     "alias": "Transmit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "interface_tx",
     "query": "SELECT 8*non_negative_derivative(mean(\"value\"), 1s) FROM \"autogen\".\"interface_tx\" WHERE (\"host\" =~ /^$hostname$/ AND \"type\" = 'if_octets' AND \"instance\" =~ /^$interface$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_octets" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$interface$/" }
     ]
    }
   ]
  },
  {
   "title": "TX Total ($hostname)",
   "type": "table",
   "gridPos": { "h": 12, "w": 5, "x": 18, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"collectd/${rp}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iptables_value\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"aggregate\"] == \"increase\")\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\n  |> filter(fn: (r) => r[\"instance\"] == \"mangle-iptmon_tx\")\n  |> filter(fn: (r) => r[\"type_instance\"] =~ /^tx_${client:regex}$/)\n  |> filter(fn: (r) => r[\"type\"] == \"ipt_bytes\")\n  |> sum()\n  |> keep(columns: [\"type_instance\",\"_value\"])  \n  |> group()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RX Total ($hostname)",
   "type": "table",
   "gridPos": { "h": 12, "w": 5, "x": 18, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"collectd/${rp}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iptables_value\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"aggregate\"] == \"increase\")\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\n  |> filter(fn: (r) => r[\"instance\"] == \"mangle-iptmon_rx\")\n  |> filter(fn: (r) => r[\"type_instance\"] =~ /^rx_${client:regex}$/)\n  |> filter(fn: (r) => r[\"type\"] == \"ipt_bytes\")\n  |> sum()\n  |> keep(columns: [\"type_instance\",\"_value\"])  \n  |> group()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TX client Traffic on $hostname",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "Receive",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "interface_rx",
     "query": "from(bucket: \"collectd/${rp}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iptables_value\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"aggregate\"] == \"${agg}_rate\")\r\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\r\n  |> filter(fn: (r) => r[\"instance\"] == \"mangle-iptmon_tx\")\r\n  |> filter(fn: (r) => r[\"type_instance\"] =~ /^tx_${client:regex}$/)\r\n  |> filter(fn: (r) => r[\"type\"] == \"ipt_bytes\")\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_octets" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$interface$/" }
     ]
    }
   ]
  },
  {
   "title": "RX client Traffic on $hostname",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "Transmit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "interface_tx",
     "query": "from(bucket: \"collectd/${rp}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iptables_value\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"aggregate\"] == \"${agg}_rate\")\r\n  |> filter(fn: (r) => r[\"bucket\"] == \"collectd\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname}$/)\r\n  |> filter(fn: (r) => r[\"instance\"] == \"mangle-iptmon_rx\")\r\n  |> filter(fn: (r) => r[\"type_instance\"] =~ /^rx_${client:regex}$/)\r\n  |> filter(fn: (r) => r[\"type\"] == \"ipt_bytes\")\r\n  ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_octets" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$interface$/" }
     ]
    }
   ]
  }
 ]
}